Add Windows Server detection, require node 4
sindresorhus/windows-release pull request #7
Opened 2017-07-22 16:00 UTC by silverwind

- Detect Windows Server 2008,2012 and 2016 via a `wmic` call
- Remove workaround for io.js 3 and older node versions
- ES2015ify

Fixes: https://github.com/sindresorhus/win-release/issues/5

2017-07-22 19:13 UTC, kevva requested changes

2017-07-22 19:13 UTC, kevva commented on index.js
>  module.exports = function (release) {
`module.exports = release => {`

2017-07-22 19:13 UTC, kevva commented on index.js
> +		const child = execa.sync('wmic', ['os', 'get', 'Caption']);
`const stdout = execa.sync('wmic', ['os', 'get', 'Caption']).stdout || '';`

2017-07-22 19:43 UTC, silverwind commented
@kevva updated.

2017-07-22 23:26 UTC, kevva approved these changes

2017-07-23 17:44 UTC, merged

2017-07-23 17:44 UTC, sindresorhus commented
Thanks for fixing @silverwind :)